# Generated by Django 4.2.5 on 2023-10-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipes_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
